### ISSUE TITLE
Value Error:('The number of weights does not match the population')

### ISSUE THREAD

**Issue by awesomekid1021** [Jon-Becker/nft-generator-py#1]
So there's a weird error that happened when I tried to run the code with my own images, I posted my images here but I'm just not sure how to solve this, can someone help?
<img width="1440" alt="Screen Shot 2021-09-17 at 11 19 17 AM" src="https://user-images.githubusercontent.com/33333641/133808013-e61d9217-4c78-47b8-9292-befa276b09df.png"
<img width="1440" alt="Screen Shot 2021-09-17 at 11 19 11 AM" src="https://user-images.githubusercontent.com/33333641/133808077-bebe3f21-b88a-4531-9f39-fb212f72e8e1.png">
<img width="1440" alt="Screen Shot 2021-09-17 at 11 19 05 AM" src="https://user-images.githubusercontent.com/33333641/133808079-de3af1ad-530b-4d5a-981e-c5b095381d8d.png">
<img width="1440" alt="Screen Shot 2021-09-17 at 11 19 04 AM" src="https://user-images.githubusercontent.com/33333641/133808080-6a1be2d3-4f5d-4ece-a248-b32dd12d8bdf.png">
<img width="1440" alt="Screen Shot 2021-09-17 at 11 18 58 AM" src="https://user-images.githubusercontent.com/33333641/133808081-093abc68-ae8d-4d1a-a001-f4fad29aa913.png">
>

**Comment by Jon-Becker** [comment]
Thats an error when the image weights don't add up to 100, but they seem to in your code. Are all the images the same size in pixels? Can you send me a zip file of your code so I can check it? Thank you!

**Comment by Jon-Becker** [comment]
Nevermind. On line 89 you only specify one value "Python Logo", but you have 2 files and 2 weights that the code is looking for.

**Comment by wsasdsda** [comment]
Have you solved this problem?

**Comment by Jon-Becker** [comment]
> Have you solved this problem?
> 
> 

yep. check your weights again
