### ISSUE TITLE
Use GIF or MP4 files in generations

### ISSUE THREAD

**Issue by KotesUA** [Jon-Becker/nft-generator-py#10]
Hello!
Is it possible to merge not PNG, but GIF or MP4 files the same way as PNG?
Can this feature be added?

**Comment by KotesUA** [comment]
This can be done by adding an option in config to create GIF from PNG sequence, by selecting an entire folder with PNGs. In this cade, GIF is processed layer by layer for each output image. Parameters for GIF may be only frames/second.

**Comment by Jon-Becker** [comment]
Considering adding this.

**Comment by Jon-Becker** [comment]
Accepted. v1.1.x will accept GIFs and PNG sequences as inputs.

**Comment by KotesUA** [comment]
[convert.txt](https://github.com/Jon-Becker/nft-generator-py/files/7587568/convert.txt)
I've done this using moviepy and mp4 output.
Pretty custom after-png-generation solution, but after all tests the quality is better than if using PIL .save even with 'optimize' parameter set to 'false'

**Comment by AndoKarim** [comment]
Hello,
I don't get what your script is doing. He's reading all the "eyes" folder and png inside and create a video of all of them? 
I thought that your question was more about merging a blinking eye gif for example with other static layers.
