### ISSUE TITLE
Increasing amount causes failure after adding more incompatibilities

### ISSUE THREAD

**Issue by Atekom** [Jon-Becker/nft-generator-py#13]
Hi there, thanks for providing this resource. It helps for learning.
Testing, I have been growing the number of incompatibilities between traits and layers.
Removing a few target blocks of incompatibilities, you can generate 1000 or more.
Adding those sections back will see premature finish with exit code -1073741571 (0xC00000FD)
However you can then generate about 200 but exceeding that will again result in EC: -1073741571 (0xC00000FD) 

Does it need more assets in this situation due to growing the number of incompatibilities limiting the total number of possible outcomes below 200?

**Comment by Jon-Becker** [comment]
Good issue. I'll take a look at a fix later tomorrow. Thanks!

**Comment by Jon-Becker** [comment]
Are you sure there are enough layers to generate amount images?

The error is encountered when it can't make any more unique images.

**Comment by Atekom** [comment]
I believe the number of possible combinations might have been reduced due to creating more and more incompatibilities. 

That would indicate so if it is only encountered after implementing increasing incompatibilities to make better outputs.

Fantastic job at efficiency it is very fun to learn about and experiment with!

**Comment by Jon-Becker** [comment]
Yeah if you add incompatibilities it cuts down how many unique images may be created. Keep that in mind when selecting an amount to generate.

Thank you for the support! If you don't need anything else, feel free to close this issue :)
