### ISSUE TITLE
Increasing "Amount" causes error

### ISSUE THREAD

**Issue by werksone** [Jon-Becker/nft-generator-py#2]
As soon as I try to increase the amount i get an error

`
    return [population[bisect(cum_weights, random() * total, 0, hi)]
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/random.py", line 505, in <listcomp>
    return [population[bisect(cum_weights, random() * total, 0, hi)]
RecursionError: maximum recursion depth exceeded in comparison
`

**Comment by Jon-Becker** [comment]
You need more layers. It's trying to create unique images but can't, because it only has a few layers to work with.

**Comment by werksone** [comment]
Ahh understood, Makes sense. Cheers.
