### ISSUE TITLE
DNA

### ISSUE THREAD

**Issue by fromMaianor** [Jon-Becker/nft-generator-py#21]
Hi Jon,

Not a dev, but had someone in exchange for some crypto to add the DNA for me.

Would you include it please in your next code update after you find a solution for below? I'll send you the zip if affirmative.

> thanks for the tip, but then i get a few combinations where the EYES are missing where they should not. sorry for bothering you :)

I will look for a solution for now. You can add an imcompatibility with EYES none with everything but ironman. It'll only pick a none layer if ironman is selected then, and never pick a none layer otherwise.

_Originally posted by @Jon-Becker in https://github.com/Jon-Becker/nft-generator-py/issues/19#issuecomment-1004190773_

**Comment by Jon-Becker** [comment]
I'm confused, sorry.

**Comment by Jon-Becker** [comment]
This issue was already fixed, you can view the solution in your linked issue. Closing this
