### ISSUE TITLE
Metadata files generated in main folder instead metadata folder

### ISSUE THREAD

**Issue by CptJackieSparrow** [Jon-Becker/nft-generator-py#25]
I don't know why, looks like code is on point but metadata files generated in main folder instead metadata folder.
Maybe you can spot the problem

**Comment by Jon-Becker** [comment]
It might be an issue with the CWD of your terminal.

**Comment by CptJackieSparrow** [comment]
Actually CWS is alright as images are stored in image folder.
It won't generate metadata's if there's no metadata folder also.
But somehow, all metadata is generated in main folder. Not a big problem though.

**Comment by Jon-Becker** [comment]
IDE, python version, and steps to reproduce?
