### ISSUE TITLE
upload tool 

### ISSUE THREAD

**Issue by omowanai** [Jon-Becker/nft-generator-py#27]
i have my nft collection created, what tool can i use to bulk upload with this metadata format ?

**Comment by omowanai** [comment]
i have modified the indexy.py to produce the proper metadata format for the up loader ive decided to use, it formats the individual json files to exact format up loader uses but im pretty sure up loader uses the all_objects.json, and my editing isnt affecting the all_objects.json, any ideas how i can get the full json files to get put into all_objects.json? thanks

**Comment by Jon-Becker** [comment]
Use an erc721 smart contract and upload metadata and images to IPFS
