### ISSUE TITLE
it is not possible to generate more than 5 nft with my config.

### ISSUE THREAD

**Issue by Puffini** [Jon-Becker/nft-generator-py#29]
the process simply dies if I set a value greater than 5, and with a standard code greater than 20 is not generated "The kernel 'Python 3.10.2 64-bit' died. "
`generate_unique_images(5, {
  "layers": [
    {
      "name": "Background",
      "values": ["Common", "Uncommon", "Rare", "Epic", "Legendary"],
      "trait_path": "./trait-layers/backgrounds",
      "filename": ["blue", "orange", "purple", "red", "yellow"],
      "weights": [40,35,15,9,1]
    },
    {
      "name": "Foreground",
      "values": ["Qw, "Qs","Qe","Qr","Qt" ],
      "trait_path": "./trait-layers/foreground",
      "filename": ["qw", "qs", "qe", "qr", "qt"],
      "weights": [20,20,20,20,20]
    },

  ],
  "incompatibilities": [
    {
      "layer": "Foreground",
      "value": "Qw",
      "incompatible_with": ["Uncommon", "Rare", "Epic", "Legendary"]
    },
    {
      "layer": "Foreground",
      "value": "Qs",
      "incompatible_with": ["Common", "Rare", "Epic", "Legendary"]
    },
    {
      "layer": "Foreground",
      "value": "Qe",
      "incompatible_with": ["Common", "Uncommon", "Epic", "Legendary"]
    },
    {
      "layer": "Foreground",
      "value": "Qr",
      "incompatible_with": ["Common", "Uncommon", "Rare", "Legendary"]
    },
     {
      "layer": "Foreground",
      "value": "Qt",
      "incompatible_with": ["Common", "Uncommon", "Rare", "Epic"]
    },
  ],
  "baseURI": ".",
  "name": "NFT #",
  "description": "Generation 0"
})`

**Comment by Jon-Becker** [comment]
See #2.

**Comment by Jon-Becker** [comment]
If that didn't solve it, let me know.

**Comment by Jon-Becker** [comment]
What do you mean?
