### ISSUE TITLE
Hi sir . I found this, what should I do?

### ISSUE THREAD

**Issue by Ozonept** [Jon-Becker/nft-generator-py#31]
![38B84F22-B728-425A-8D01-7A9217C75EDE](https://user-images.githubusercontent.com/100385433/155615751-b3b40cc8-76af-41c7-ace3-27d2ff16dd2e.jpeg)
![2D4BBD8B-E9AE-4019-861B-84D7973BB27C](https://user-images.githubusercontent.com/100385433/155615768-15a8d516-1a7d-4b00-b5e6-bb0c879b97ad.jpeg)

**Comment by Jon-Becker** [comment]
Hey! Look's like this was already mentioned in #14 and #6. If you need further help, let me know.
