### ISSUE TITLE
Cant Generate

### ISSUE THREAD

**Issue by PetreEP** [Jon-Becker/nft-generator-py#32]
Hello, First of all thank you for amazing work.

 I'm very noobie, first time trying to do something in .py.

I just wanted to check if your generator engine is work. I didn't change anything, but all the time have same error 

Exception has occurred: ModuleNotFoundError
No module named 'PIL'
  File "[/Users/petre/Desktop/NFT-PY/index.py]()", line 2, in <module>
    from PIL import Image

Could you help me?

**Comment by Jon-Becker** [comment]
Hey!

You need to install the requirements. You can do this by running
`pip install requirements.txt`

**Comment by PetreEP** [comment]
Will try, thank you very much!

**Comment by Jon-Becker** [comment]
Howd it work?

**Comment by PetreEP** [comment]
Didn’t find yesterday how to run pip install requirements on mac. It’s my second time with programing :)) I tried hashlips engine it works fine but in your generator i like that i can use if statement in layers/traits. Will try tomorrow to find any guide how to install pip. Thank  for your attention!

**Comment by PetreEP** [comment]
Sorry for disturbing, one more question i got error at line 67 

/usr/bin/python2.7 /Users/petre/Desktop/nft-generator-py-1.0.2/index.py
  File "/Users/petre/Desktop/nft-generator-py-1.0.2/index.py", line 67
    layers[index] = Image.open (f'{config["layers"][index]["trait_path"]}/{trait_files[attr][item[attr]]}.png').convert('RGBA')
                                                                                                             ^
SyntaxError: invalid syntax

Could you help me?

**Comment by PetreEP** [comment]
Hey mate, i sat up all the Libraries and everything is working perfect. Thank you!

**Comment by PetreEP** [comment]
Hey Joh, I was using your nft for test collection and everything worked perfectly, but when I have started generating of full collection suddenly i have this issue 

TERM environment variable not set.
Traceback (most recent call last):
  File "/Users/petre/Desktop/Mutual Friends Generator/index.py", line 102, in <module>
    generate_unique_images(5, {
  File "/Users/petre/Desktop/Mutual Friends Generator/index.py", line 66, in generate_unique_images
    layers[index] = Image.open(f'{config["layers"][index]["trait_path"]}/{trait_files[attr][item[attr]]}.png').convert('RGBA')
KeyError: ‘trait_path'

I checked all size of all pictures and seems it’s similar 3000 X 3000
I also checked all image & layer names and they are correct.

Could you help me ?


Best Regards,

Petre
