### ISSUE TITLE
Metadata issue

### ISSUE THREAD

**Issue by PetreEP** [Jon-Becker/nft-generator-py#34]
Hey, Everything works fine, except metadata name and token id inside. For exmp. When 5 image generation have completed I've got:

In image Folder: 1,2,3,4,5

In metadata Folder: 0,1,2,3,4 and all objects.

I have qustion if it's possible to match token id number to metadata number. 

Thanks,

Petrre

**Comment by menezesphill** [comment]
> Hey, Everything works fine, except metadata name and token id inside. For exmp. When 5 image generation have completed I've got:
> 
> In image Folder: 1,2,3,4,5
> 
> In metadata Folder: 0,1,2,3,4 and all objects.
> 
> I have qustion if it's possible to match token id number to metadata number.
> 
> Thanks,
> 
> Petrre

This behavior is not expected. I have just run an example on my local environment, and it is working as it should, generating images and metadata files with matching ids. Does your console throw any errors or warnings?

**Comment by Jon-Becker** [comment]
@PetreEP Steps to reproduce?

**Comment by Jon-Becker** [comment]
I'll need your configuration too

**Comment by PetreEP** [comment]
Fixed it! All good now! Thx for answer.
