### ISSUE TITLE
Use a command line interface instead of python script args

### ISSUE THREAD

**Issue by mteam88** [Jon-Becker/nft-generator-py#44]
The current call is `python script.py *args`

It would be more useful to have it be `script *args` because it would be usable by users without the `python` tool working and it improves abstraction.

You can use a few libraries for this including `Click`.

**Comment by Jon-Becker** [comment]
You can add the script to your path if you want this rn

Soon after the refactor it will be installed via pip and will have this functionality

**Comment by mteam88** [comment]
Sounds good!
