### ISSUE TITLE
Where to enter amount of nft i want to generate?

### ISSUE THREAD

**Issue by PetreEP** [Jon-Becker/nft-generator-py#48]
Hey in the previous version there was a line "generate_unique_images (50, {"

In the updated 2.0 version I can't find where should I enter the amount :(  I have this error now: "heimdall: error: Missing a mandatory option (-n or -c). Use -h to show the help menu"

**Comment by Jon-Becker** [comment]
The module uses argparse now, so you tell it how many to generate using the `-n` flag. To tell it what config to use, use the `-c` flag.

Ex: `generate.py -n 10 -c config.json`

**Comment by PetreEP** [comment]
Got it! Thank you
