### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by sriharsh1104** [Jon-Becker/nft-generator-py#49]
Feature Request:

When deploying the NFT images and metadata to IPFS, it is necessary to first upload the images (and get a unique CID).
Then I need to update the JSON files to point at this CID. I can not create the CID in advance of running the generative script (index.py) as I do not have the CID until I upload the images.

Could a script be added to run after the index.py & once I get the CID to go through all files in the metadata folder and update the baseURI to represent the IPFS CID? (Or regenerate them based on all-object.json?) Obviously the data needs to maintain the connection to the image. is these feature possible if yes than can you share a video reference or doc for the same .

_Originally posted by @sriharsh1104 in https://github.com/Jon-Becker/nft-generator-py/issues/7#issuecomment-1477580989_

**Comment by Jon-Becker** [comment]
Does this not solve this issue?

https://github.com/Jon-Becker/nft-generator-py/blob/main/update_cid.py
