### ISSUE TITLE
Add ability to block two or more traits from combining

### ISSUE THREAD

**Issue by stocktonellis** [Jon-Becker/nft-generator-py#5]
As a user, I want to be able to configure the script to block certain elements from combining. 

For example:
If my project has 2 traits: eyes and glasses. 
One of my eyes are have an attribute of "popping out". 
If the eyes are "popping out" I do not want glasses to be added. 
All other eye attributes would be OK to apply glasses to according to.

**Comment by Jon-Becker** [comment]
https://github.com/Jon-Becker/nft-generator-py/releases/tag/v1.0.1
