### ISSUE TITLE
Float Validation

### ISSUE THREAD

**Issue by Whanod** [Jon-Becker/nft-generator-py#59]
No matter how i change the weights array i get something like this :

src.common.exceptions.ConfigValidationError: config["layers"][3]["weights"]: The sum of the weights must be 100. Current sum: 100.00000000000006

my weights
      "weights": [
        1.4, 1.4, 1.4, 1.4, 2.5, 1.4, 1.7, 9.2, 2.5, 1.4, 0.3, 1.7, 1.7, 1.2,
        0.7, 1.4, 0.9, 1.4, 1.7, 0.5, 1.7, 1.4, 0.2, 1, 2.2, 1.7, 1.8, 1.4, 1.7,
        1.4, 1.7, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.7, 1.7, 1.8, 1.7, 1.4,
        1.4, 1.7, 2, 0.7, 1.8, 0.9, 1.8, 1.4, 1.4, 1.4, 1.7, 1.7, 1.8, 1.7, 1,
        1.7, 1.4, 0.9, 1.7, 1.8
      ]

**Comment by Jon-Becker** [comment]
i love python

will tackle tomorrow. please ping me if i forget!

**Comment by Jon-Becker** [comment]
on it
