### ISSUE TITLE
Getting List index out of range error.

### ISSUE THREAD

**Issue by stocktonellis** [Jon-Becker/nft-generator-py#6]
When I try to run the program with my attributes, I keep getting this error: Not sure why? I did add more traits and values than the original. Any ideas?

% python3 index.py

Traceback (most recent call last):
  File "/Users/NAME/Desktop/nft-generator/index.py", line 83, in <module>
    generate_unique_images(8888, {
  File "/Users/NAME/Desktop/nft-generator/index.py", line 28, in generate_unique_images
    trait_files[trait["name"]][key] = trait["filename"][x];
IndexError: list index out of range

**Comment by Jon-Becker** [comment]
Please upload your configuration

**Comment by stocktonellis** [comment]
[tmpxov4emqu.pdf](https://github.com/Jon-Becker/nft-generator-py/files/7458326/tmpxov4emqu.pdf)

**Comment by Jon-Becker** [comment]
Looks like the PDF cuts it off.

**Comment by stocktonellis** [comment]
Will do later tonight.

**Comment by Jon-Becker** [comment]
Sounds good, thank you!

**Comment by Jon-Becker** [comment]
```
{
      "name": "Mouth",
      "values": ["Closed", "Frown", "Golden-Teeth", "Grumpy", "Smile", "Snorkle", "Tounge-Out", "Mouth-none"],
      "trait_path": "./trait-layers/Mouth",
      "filename": ["blue", "orange", "purple", "red", "yellow"],
      "weights": [10,15,4,3.9,20,.1,14,33]
    },
    ```
    
    Lines 120-126. Looks like the Values don't match the filenames, which would cause the error you showed.
