### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by ccislegend** [Jon-Becker/nft-generator-py#9]
Hi, after editing the config, I am receiving a Index Error: list index out of range, 

I saw in previous issue this could be syntax or mismatch with layer files in folders. I quadruple checked my files and filenames but still receive the error. I have a lot of different traits as well as fractional weights. 

Generating 2500 unique NFTs...
Traceback (most recent call last):
  File "C:\Users\colin\Documents\NFTs\Froggos\Froggos Generator\Generator\nft-generator-py\index.py", line 110, in <module>
    generate_unique_images(2500, {
  File "C:\Users\colin\Documents\NFTs\Froggos\Froggos Generator\Generator\nft-generator-py\index.py", line 35, in generate_unique_images
    trait_files[trait["name"]][key] = trait["filename"][x]
IndexError: list index out of range
PS C:\Users\colin\Documents\NFTs\Froggos\Froggos Generator\Generator\nft-generator-py>

**Comment by Jon-Becker** [comment]
See #6. A layer in your configuration is wrong.

**Comment by ccislegend** [comment]
I have hundreds of traits, so it took a while but managed to find the culprit. Thanks again!
